# 应用服务 WEB 访问端口
server:
        port: 8080
# 应用名称
spring:
        application:
                name: lfvueblog
        datasource:
                druid:
                        driver-class-name: com.mysql.cj.jdbc.Driver
                        url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
                        username: root
                        password: zyp66888
mybatis-plus:
        configuration:
                #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
                map-underscore-to-camel-case: true
                log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



